export const words = [
  "animal",
  "auto",
  "anecdote",
  "alphabet",
  "all",
  "awesome",
  "arise",
  "balloon",
  "basket",
  "bench",
  "best",
  "birthday",
  "book",
  "briefcase",
  "camera",
  "camping",
  "candle",
  "cat",
  "cauliflower",
  "chat",
  "children",
  "class",
  "classic",
  "classroom",
  "coffee",
  "colorful",
  "cookie",
  "creative",
  "cruise",
  "dance",
  "daytime",
  "dinosaur",
  "doorknob",
  "dine",
  "dream",
  "dusk",
  "eating",
  "elephant",
  "emerald",
  "eerie",
  "electric",
  "finish",
  "flowers",
  "follow",
  "fox",
  "frame",
  "free",
  "frequent",
  "funnel",
  "green",
  "guitar",
  "grocery",
  "glass",
  "great",
  "giggle",
  "haircut",
  "half",
  "homemade",
  "happen",
  "honey",
  "hurry",
  "hundred",
  "ice",
  "igloo",
  "invest",
  "invite",
  "icon",
  "introduce",
  "joke",
  "jovial",
  "journal",
  "jump",
  "join",
  "kangaroo",
  "keyboard",
  "kitchen",
  "koala",
  "kind",
  "kaleidoscope",
  "landscape",
  "late",
  "laugh",
  "learning",
  "lemon",
  "letter",
  "lily",
  "magazine",
  "marine",
  "marshmallow",
  "maze",
  "meditate",
  "melody",
  "minute",
  "monument",
  "moon",
  "motorcycle",
  "mountain",
  "music",
  "north",
  "nose",
  "night",
  "name",
  "never",
  "negotiate",
  "number",
  "opposite",
  "octopus",
  "oak",
  "order",
  "open",
  "polar",
  "pack",
  "painting",
  "person",
  "picnic",
  "pillow",
  "pizza",
  "podcast",
  "presentation",
  "puppy",
  "puzzle",
  "react",
  "recipe",
  "release",
  "restaurant",
  "revolve",
  "rewind",
  "room",
  "run",
  "secret",
  "seed",
  "ship",
  "shirt",
  "should",
  "small",
  "spaceship",
  "stargazing",
  "skill",
  "street",
  "style",
  "sunrise",
  "taxi",
  "tidy",
  "timer",
  "together",
  "tooth",
  "tourist",
  "travel",
  "truck",
  "under",
  "useful",
  "unicorn",
  "unique",
  "uplift",
  "uniform",
  "vase",
  "violin",
  "visitor",
  "vision",
  "volume",
  "view",
  "walrus",
  "wander",
  "world",
  "winter",
  "well",
  "whirlwind",
  "x-ray",
  "xylophone",
  "yoga",
  "yogurt",
  "yoyo",
  "you",
  "year",
  "yummy",
  "zebra",
  "zigzag",
  "zoology",
  "zone",
  "zeal",
];

export const anagrams = [
  { word: "animal", anagrams: ["lamina"] },
  { word: "arise", anagrams: ["raise"] },
  { word: "best", anagrams: ["bets"] },
  { word: "candle", anagrams: ["lanced"] },
  { word: "cat", anagrams: ["act", "tac"] },
  { word: "creative", anagrams: ["reactive"] },
  { word: "dream", anagrams: ["armed"] },
  { word: "free", anagrams: ["reef"] },
  { word: "glass", anagrams: ["slags"] },
  { word: "green", anagrams: ["genre"] },
  { word: "great", anagrams: ["grate"] },
  { word: "icon", anagrams: ["coin"] },
  { word: "kind", anagrams: ["dink"] },
  { word: "late", anagrams: ["teal", "tale", "alte"] },
  { word: "lemon", anagrams: ["melon"] },
  { word: "marine", anagrams: ["remain"] },
  { word: "moon", anagrams: ["mono"] },
  { word: "name", anagrams: ["mane", "mean"] },
  { word: "night", anagrams: ["thing"] },
  { word: "north", anagrams: ["thorn"] },
  { word: "nose", anagrams: ["ones", "eons"] },
  { word: "open", anagrams: ["nope"] },
  { word: "react", anagrams: ["trace", "caret"] },
  { word: "room", anagrams: ["moor"] },
  { word: "small", anagrams: ["malls"] },
  { word: "timer", anagrams: ["miter", "remit"] },
  { word: "vase", anagrams: ["save"] },
];
